services:
  db:
    container_name: coursehub-db
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=coursehub
      - POSTGRES_PASSWORD=coursehub
      - POSTGRES_MULTIPLE_DATABASES=usersdb,coursesdb
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - coursehubnet

networks:
  coursehubnet:
    name: coursehubnet

volumes:
  db:
