services:
  db:
    container_name: coursehub-db
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=coursehub-db
      - POSTGRES_USER=coursehub
      - POSTGRES_PASSWORD=coursehub
    ports:
      - 5432:5432
    networks:
      - coursehubnet

networks:
  coursehubnet:
    name: coursehubnet
