[tool.poetry]
name = "coursehub"
version = "0.1.0"
description = "Simple Course hub application"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
gevent = ">=23.7,<25.0"
flask = "^3.0.3"
sanctumlabs-dbkit = "^1.0.0"
flask-injector = "^0.15.0"
uvicorn = "^0.30.3"
fastapi = "^0.111.1"
pydantic-settings = "^2.3.4"
psycopg2 = "^2.9.9"
python-multipart = "^0.0.9"
nanoid = "^2.0.0"
pydantic-extra-types = "^2.9.0"
bcrypt = "^4.2.0"
alembic = "^1.13.2"

[tool.poetry.dev-dependencies]
pylint = "^3.2.6"
pytest = "^8.3.2"
black = "^24.4.2"
pre-commit = "^3.8.0"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
