[tool.poetry]
name = "kvault"
version = "0.1.0"
description = "Simple Miniature key-value datastore"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
gevent = ">=23.7,<25.0"

[tool.poetry.dev-dependencies]
pylint = "^3.2.2"
pytest = "^8.2.2"
black = "^24.4.2"
pre-commit = "^3.7.1"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
