[tool.poetry]
name = "coursehub"
version = "0.1.0"
description = "Simple Course hub application"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
gevent = ">=23.7,<25.0"
flask = "^3.1.0"
sanctumlabs-dbkit = "^1.0.0"
flask-injector = "^0.15.0"
uvicorn = "^0.34.0"
fastapi = "^0.115.12"
pydantic-settings = "^2.8.1"
psycopg2 = "^2.9.10"
python-multipart = "^0.0.20"
nanoid = "^2.0.0"
pydantic-extra-types = "^2.10.3"
bcrypt = "^4.3.0"
alembic = "^1.15.1"

[tool.poetry.dev-dependencies]
pylint = "^3.3.6"
pytest = "^8.3.5"
black = "^25.1.0"
pre-commit = "^4.2.0"
python-dotenv = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
