[tool.poetry]
name = "coursehub"
version = "0.1.0"
description = "Simple Course hub application"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
gevent = ">=23.7,<25.0"
flask = "^3.0.3"
sanctumlabs-dbkit = "^1.0.0"
flask-injector = "^0.15.0"
uvicorn = "^0.32.0"
fastapi = "^0.115.4"
pydantic-settings = "^2.6.1"
psycopg2 = "^2.9.10"
python-multipart = "^0.0.17"
nanoid = "^2.0.0"
pydantic-extra-types = "^2.10.0"
bcrypt = "^4.2.0"
alembic = "^1.14.0"

[tool.poetry.dev-dependencies]
pylint = "^3.3.1"
pytest = "^8.3.3"
black = "^24.10.0"
pre-commit = "^4.0.1"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
